### ISSUE TITLE
Not seeing "Savewapper", "Live Tuning" or "Cool Shit"

### ISSUE THREAD

**Issue by WildWiryClam** [Yeethan69/AIO#10]
Steam version. The three options I have listed are greyed out and I cannot click into these menus. Everything else works.

**Comment by ItsLogic** [comment]
These tabs are greyed out as they are not yet supported on your platform (presumably FH5 steam)
Saveswapper does not work on FH5, Live Tuning and Cool Shit have not been ported to FH5 steam yet
