### ISSUE TITLE
[Feature-Request]: 

### ISSUE THREAD

**Issue by TheNo49** [Yeethan69/AIO#100]
### Game

FH5

### What feature are you requesting?

Please make change original owner name of the cars
looks like thumbnail fix tool cahange every cars original owner name
to r/ForzaModding i want to change it back to mine

**Comment by ItsLogic** [comment]
no this is a deliberate choice to "watermark" savegames which are edited using fix thumbnails usually before getting sold(which we do not agree with and try to discourage). This feature is not needed unless you go around deleting your savedata for fun
