### ISSUE TITLE
[Feature-Request]: Translate app in some languages

### ISSUE THREAD

**Issue by PoloNX** [Yeethan69/AIO#101]
### Game

FH5

### What feature are you requesting?

Hi, if you are okay you can ask to the community to translate your app in other languages to add them in the app. 
I can translate in french if you want

**Comment by ItsLogic** [comment]
This is a duplicate of #60 so im going to close it but language support is still quite a while away
Its just not feasable to add it to the current codebase but we may add it to the V2 rewrite that is currently underway
