### ISSUE TITLE
[Bug]: Not attaching to FH5

### ISSUE THREAD

**Issue by Baz1205** [Yeethan69/AIO#104]
### What version of the aio were you running?

0.0.0.50

### Game

FH5

### Game Version

Cracked (other) Please put the crack name/version into the issue box below

### What is the bug?

Codex crack game version 1.478.20.0

AIO not attaching to game. Have tried it a few times.

**Comment by quiet69** [comment]
the AIO only works for the latest version of the game. Please update game

**Comment by Baz1205** [comment]
Okay thanks.
