### ISSUE TITLE
a bunch of features dont work on MS Version

### ISSUE THREAD

**Issue by Boosted213** [Yeethan69/AIO#11]
the tp dont work as well as velocity and the acceleration and gravity dont work

**Comment by BAWANGSONG** [comment]
ye and add all cars doesnt either

**Comment by ItsLogic** [comment]
Can you give a list of what doesnt work and what actually happens when you try to use them? does it error? does nothing happen?
could you also try other stuff on the tool like the all cars filter for the autoshow and report if that works?

**Comment by superboom7** [comment]
> ye and add all cars doesnt either

yea dosent work for me either

**Comment by MRdoomauzz** [comment]
> > ye and add all cars doesnt either
> 
> yea dosent work for me either

it worked just fine for me. There was an update for the game today, so now it really wont work until they update the AIO itself

**Comment by ItsLogic** [comment]
op didnt give any extra information. Has been almost 4 weeks with no response.

Please reopen if this issue still exists and if you want to give more information
