### ISSUE TITLE
[Feature-Request]: 

### ISSUE THREAD

**Issue by breesonvfx** [Yeethan69/AIO#123]
### Game

FH5

### What feature are you requesting?

could you guys consider being able to change amount o player wheelspins/ adding wheelspins aswell as being able to change certain statistics such as being able to change forzathon points and skill points.

**Comment by supersonik1337** [comment]
no matter how devs decide about this
this is obviously the way to the ban.

**Comment by MRdoomauzz** [comment]
I got one of my alt accounts banned for trying to edit my credits through the stats editor. Would not be surprised if they banned people for doing the same with wheel spins

**Comment by breesonvfx** [comment]
I don’t think it can lead to bans because I used to use stand for fh5 and I gave myself 3k super wheel spins and 10 norm ones and to this day I’m not banned yet, but I would like a top up and as to the skill points I don’t think they can directly get you banned either but I’m not too sure

**Comment by Yeethan69** [comment]
Not adding.
