### ISSUE TITLE
[Bug]: Game keeps crashing 

### ISSUE THREAD

**Issue by ActualFinesse** [Yeethan69/AIO#129]
### What version of the aio were you running?

0.0.0.52

### Game

FH5

### Game Version

Microsoft store

### What is the bug?

I used the aio once and it worked but ever since I try to play now the game just crashes, the game opens but when i hit "continue" in the main menu it inmediately crashes. I've tried deleting the aio, reinstalling the game and its still the same

**Comment by ActualFinesse** [comment]
So, I’m assuming the account got banned or something because it will work if I just switch accounts but my main one keeps the game crashing. Is there a ban where I can’t even open the game?

**Comment by MRdoomauzz** [comment]
I've never heard of that, but I do know first hand that you can get hardware banned from online play

**Comment by ActualFinesse** [comment]
Yeah, I get the online play ban but the game just doesn’t start at all with my main account but starts just fine when I switch

**Comment by dr-NHA** [comment]
> Yeah, I get the online play ban but the game just doesn’t start at all with my main account but starts just fine when I switch

Your Main Account Was Corrupted By The Terrible Code In This NOT Open Source Project,
If U Wish To Trust Something On Github Check For Sourcecode :)
HEY YEETHAN!

**Comment by dr-NHA** [comment]
To Fix The Issue Please Delete WGS In Your Games Appdata Folder (Found In Packaged And Game Name)
U Can Look This Up,
Then Open The Game With Your Main And Dont Sync The Gamesave,
Your Gamesave Is Gone FOREVER Sadly,
Shouldnt Use Free NON Open Source Software!

**Comment by ActualFinesse** [comment]
This absolutely fixes the issue, thank you so much!!!
