### ISSUE TITLE
SKILL POINTS DONT WORK AIO

### ISSUE THREAD

**Issue by Codyperkins2** [Yeethan69/AIO#14]
when I edit the skill points nothing changes on the account.  Am I doing some thing  wrong or could u plz tell step by step how to get it working

**Comment by KKirschi** [comment]
For me too. Followed the Discord instructions corretly but nothing happened.

**Comment by Yeethan69** [comment]
I'm pretty sure it only works if you have never been refunded skill points on your account before, such as the willy jeep glitch.

**Comment by Yeethan69** [comment]
Nothing more to add
