### ISSUE TITLE
The AIO doesn't work after latest game update

### ISSUE THREAD

**Issue by neXus0** [Yeethan69/AIO#18]
Hello, the game got updated a few hours ago, the tool doesn't attach to FH5 anymore : 

![image](https://user-images.githubusercontent.com/10615198/144655034-1067d0e6-0c21-41f7-9238-11ffbe43ebb7.png)

Can you look into this when you have time to do so ?
Thanks

**Comment by neXus0** [comment]
it stays stuck here : 

![image](https://user-images.githubusercontent.com/10615198/144655144-90f6cb03-e6be-45b2-b1f3-52fea9bcddbe.png)

**Comment by Yeethan69** [comment]
We know, we need to update the tool.
