### ISSUE TITLE
AIO won't attach after updating to 0.0.0.18. Progress bar gets stuck

### ISSUE THREAD

**Issue by NIPSLIP** [Yeethan69/AIO#24]
![Screenshot 2021-12-04 215525](https://user-images.githubusercontent.com/95555551/144731723-4d2dacff-1f62-4a21-9433-b67734165bb1.jpg)

**Comment by ikhzter** [comment]
Same for me. Stuck on that. 
Restarted PC, Ran tool as Admin, also tried windows 8 compatibility mode. Ca't get passed 10%

**Comment by SMURFYcrap** [comment]
ive been waiting for it to attach aswell.

**Comment by VandilFish** [comment]
Having the same issue. Been waiting over 30 minutes and hasn't moved.

**Comment by ItsLogic** [comment]
The way the tool attaches to the game was changed this update to try and make it more friendly towards game updates(possibly working across game versions without us needing to update it) but it seems to have broken attaching completely on some peoples systems.

We are working on a fix although I dont know when it will release.

In the meantime though waiting any longer than a few mins with 0 progress changes in the bar is a waste of time. I would say either close the AIO and dont use it or restart the game and hope it attaches the next time

**Comment by PsychoManiac189** [comment]
AIO IS STILL BROKE

**Comment by Yeethan69** [comment]
no, it isn't, and if it is, there is a temporary fix pinned in the forza chat of the discord.
