### ISSUE TITLE
Patch version in the release notes will help understand which version of the game the release supports

### ISSUE THREAD

**Issue by wrick17** [Yeethan69/AIO#29]
I just found out that the v18 is actually for the last nov release. On Github it showed it was released 2 days ago, so I assumed it was updated to the latest Dec 3 patch. Maybe it'll help if the releases also mentioned the patch they support. Thanks.

![image](https://user-images.githubusercontent.com/8253932/144976877-da88e0b5-118e-4034-93a5-2ed0d49b6e7b.png)

**Comment by ItsLogic** [comment]
v18 is updated for the December 3rd patch (the date in the app is wrong as @Yeethan69 forgot to change it before releasing). Adding game version to release notes is a good idea though we will do that moving forward

**Comment by pratyushok** [comment]
@ItsLogic Well then free perf upgrades don't work for me. They still show their usual costs. Whereas visual upgrades work just fine.

**Comment by wrick17** [comment]
@ItsLogic Well then free perf upgrades don't work for me. They still show their usual costs. Whereas visual upgrades work just fine.

**Comment by ItsLogic** [comment]
Closing this as we never actually tagged releases with version numbers and no longer have any plans to. If the user wants to be sure they can check https://support.forzamotorsport.net/hc/en-us/sections/4408834302355-Release-Notes-and-Known-Issues
