### ISSUE TITLE
AIO wont attach to FH5 Fully

### ISSUE THREAD

**Issue by SilentBloody** [Yeethan69/AIO#3]
I'm not sure whats going on but when I launched the tool it didn't let me attach to fh5. Before it was working great. I updated the tool to the Latest Version already too.
P.S. I waited for the tool to attach for 10 min. but the bar is stuck there not attaching.

![Screenshot 2021-11-17 173622](https://user-images.githubusercontent.com/93749549/142335233-c7485b6a-1375-497c-8621-63a419b3c81a.png)

**Comment by Yeethan69** [comment]
The tool is not updated for the latest update of fh5 yet.
It is being developed with new features in the works ready for next update, which _should_ be tomorrow.
