### ISSUE TITLE
AIO Attach Bar Freezing

### ISSUE THREAD

**Issue by fearandesire** [Yeethan69/AIO#30]
Since the Dec update, the AIO tool stops loading about an inch of the way through. Attached an image to help show what I mean.

![image](https://user-images.githubusercontent.com/63979371/145111299-1d2c2e40-2f43-4bec-9f19-2b5971ac711c.png)

**Comment by pratyushok** [comment]
@fearandesire try the latest build. Remember only to launch the tool once you're in the game on the road or in the garage. Don't start before that.

**Comment by fearandesire** [comment]
> 

I am using the latest 0.0.0.18 build, and I am only loading it when I launch and am in the road. Any other suggestions?

**Comment by SilentBloody** [comment]
I have the same issue i relaunched it while I'm driving still didn't work

**Comment by fearandesire** [comment]
> I have the same issue i relaunched it while I'm driving still didn't work

Just fuck us I guess huh?

**Comment by fearandesire** [comment]
fixed in latest update, thank you 👍
