### ISSUE TITLE
0.18 no longer hooks to process

### ISSUE THREAD

**Issue by x-NiM-x** [Yeethan69/AIO#32]
as of  December 15th 2021 AIO 0.18 no longer works with forza horizon 5 due to the recent update FH5 has had.

**Comment by Nlgaming** [comment]
Same!!!

**Comment by LegitSoulja** [comment]
They all know, and currently working on an update. Be patient.

**Comment by ItsLogic** [comment]
Tool has been updatee for latest game version. Closing the issue
