### ISSUE TITLE
not connecting to my game 

### ISSUE THREAD

**Issue by kushcreationsuk** [Yeethan69/AIO#37]
the bar loads low a tiny bit and then nothing else happens at all

**Comment by Yeethan69** [comment]
Just released a hotfix that should fix this issue, reply back telling me if it did or not

**Comment by kushcreationsuk** [comment]
Yeah thats defo fixed it mate i have found another issue though the add all cars doesnt seem to be working for me

**Comment by kushcreationsuk** [comment]
ive watched the video guide and copied it like 5 times and nothing ever happens :/
