### ISSUE TITLE
the add all cars doesnt seem to be working

### ISSUE THREAD

**Issue by kushcreationsuk** [Yeethan69/AIO#38]
the add all cars doesnt seem to be working, ive watched the guide tried it a few times now and nothing ever happens and im playing on the MS version if that helps at all

**Comment by Wolfy6848** [comment]
> the add all cars doesnt seem to be working, ive watched the guide tried it a few times now and nothing ever happens and im playing on the MS version if that helps at all

for me when im done i go onto settings then leave settings and it says cars have been added to garage

**Comment by TheChxice** [comment]
You need to be online for cars to be added aka WiFi connection or Lan turned om

**Comment by ItsLogic** [comment]
please comment in #56 with information to help us fix the issue
