### ISSUE TITLE
Free performance option isn't working!

### ISSUE THREAD

**Issue by Airwind98** [Yeethan69/AIO#4]
Free Perf Parts doesn't seem to work for some reason!

**Comment by Yeethan69** [comment]
Make sure to read the text guide as free upgrades are done differently to the other options, also, the aio is not updated for the current fh5 version.

**Comment by Airwind98** [comment]
hey, bro, I'm back again there was a trainer update today after that It stopped detecting the game for some reason & doesn't work!

**Comment by Yeethan69** [comment]
The updated tool is for the newest game updated, so if you haven't updated your game, the tool wont connect. Version 0.0.0.15 should still work for the previous version.

**Comment by ItsLogic** [comment]
can you confirm if this issue still exists in the new version?

**Comment by wrick17** [comment]
I can confirm that the Free performance option does not work with the Dec 3rd update.

**Comment by ItsLogic** [comment]
This has been fixed now and op did not confirm if it was still broken. Closing this issue

If it is still broken please reopen
