### ISSUE TITLE
0.24 Not injecting into game MS Store version

### ISSUE THREAD

**Issue by WSTGClips** [Yeethan69/AIO#40]
0.24 Not injecting into game MS Store version

**Comment by bpeterz** [comment]
> 0.24 Not injecting into game MS Store version

Same for me

**Comment by x-NiM-x** [comment]
Not sure what's going on over on your ends, but its working fine for me. Gotta be in game at the garage or driving

**Comment by bpeterz** [comment]
> Not sure what's going on over on your ends, but its working fine for me. Gotta be in game at the garage or driving

Works now thanks!

**Comment by MRdoomauzz** [comment]
Does anyone play Steam version and is able to get it to connect?

**Comment by MRdoomauzz** [comment]
> > Not sure what's going on over on your ends, but its working fine for me. Gotta be in game at the garage or driving
> 
> Works now thanks!

Wont connect for me

**Comment by LegitSoulja** [comment]
I think "Injecting" is the wrong word to use here. Memory editing is what this tool does. It doesn't inject any modules into the game.

**Comment by ItsLogic** [comment]
closing as tool is no longer on version 0.24 and the attaching has been fixed
