### ISSUE TITLE
is there a way to add Forzaton Points?

### ISSUE THREAD

**Issue by KKirschi** [Yeethan69/AIO#46]
is there a way to add Forzaton Points (FP)? The ones you spend on the shop?
For now, I only know cheating yourself skillpoints and then tuning specific cars to give yourself FP points, but is there a quicker method?

**Comment by ItsLogic** [comment]
There is not a way that is publicly known and there is currently no plan to add this feature to the AIO

**Comment by KKirschi** [comment]
ok, thanks
