### ISSUE TITLE
Feature Request/ Enlightment

### ISSUE THREAD

**Issue by anirudh-pixel** [Yeethan69/AIO#47]
Can u please add a feature to unlock all player customization items like jackets/shirts/horns /emotes etc. in fh4 in one click like the quick add all cars feature?
Also if the ability to do so is already present please explain how to do it.

**Comment by ItsLogic** [comment]
a clothing unlocker has been added under the cool shit tab.
Emotes and horns have not but will be if/when a method to get them is found
