### ISSUE TITLE
Add all cars got me banned, Owens Mclaren

### ISSUE THREAD

**Issue by Edgarhighmen** [Yeethan69/AIO#48]
Acquired a Mclaren that apparently gets you banned. Removed it with AIO. Never drove it. Used AIO to remove it. I'm responsible for my actions, any way to fix this?

**Comment by anirudh-pixel** [comment]
Mclaren owen is instant banned no matter how it came to your garage.
This was a car made for a special person coz he had some special needs and was never released to public that is only one copy of the car is their in the whole forza horizon 4 server.
The above ban is hwid ban that means you need to spoof your hwid or HARD reset your pc deleting everything completely, and not just deleting selecting the option that makes files unrecoverable after resetting.
one hwid spoofer is posted on the discord group.

above mclaren owen ban happened to me also thats why i know.

**Comment by LegitSoulja** [comment]
"any way to fix this?"
Nope. Reinstall your OS, make a new xbox account and buy the game again.

**Comment by Yeethan69** [comment]
> "any way to fix this?" Nope. Reinstall your OS, make a new xbox account and buy the game again.

you don't need to buy the game again, you can sign into the microsoft store with the account you bought the game with. as long as you don't sign into the xbox app with the banned account, you should be fine (after a hwid spoof or reinstall).

**Comment by LegitSoulja** [comment]
> > "any way to fix this?" Nope. Reinstall your OS, make a new xbox account and buy the game again.
> 
> you don't need to buy the game again, you can sign into the microsoft store with the account you bought the game with. as long as you don't sign into the xbox app with the banned account, you should be fine (after a hwid spoof or reinstall).

I thought signing into the banned account on windows regardless of the app would link both new and old accounts in a way making the new account banned? How would you family share the game if you can't log into the Xbox App? You would have to purchase the game again, since you can't install the app from the Windows Store anymore, it's all directed to the Xbox app now.

**Comment by KarmaMod** [comment]
Would it be possible to prevent this car from being added while adding all cars?

**Comment by ItsLogic** [comment]
Owens mclaren is added to the add all cars blacklist. It will still show up under the add cars and rare cars filter for the autoshow though.

**Comment by KarmaMod** [comment]
Ok nice!
