### ISSUE TITLE
limited edition xbox controller dlc car not adding to garage.

### ISSUE THREAD

**Issue by anirudh-pixel** [Yeethan69/AIO#49]
This car (Forza Horizon 5 - 1932 Ford De Luxe Five-Window Coupe Forza Edition ) is only available to buy for those who buy limited edition fh5 controller. I can see this car in autoshow after selecting show all cars in mod tool but can't buy it.
Please fix if possible.

**Comment by LegitSoulja** [comment]
It's a DLC you don't own, which AIO doesn't unlock DLC's.

**Comment by ItsLogic** [comment]
The aio does not unlock paid DLC content and never will. This is not a bug its DRM from the game
