### ISSUE TITLE
is the tool updated already?

### ISSUE THREAD

**Issue by supersonik1337** [Yeethan69/AIO#5]
yesterday was an update deployed for fh5 and i wanna ask if the tool is updated already?

**Comment by my-dad-beats-me** [comment]
Not yet. They posted in the discord yesterday that the aio didn't work with with the latest patch and that there'll be an update soon, as well as updated the aioUpdate.txt, and they have been responding to comments on their YouTube videos about the patch

**Comment by supersonik1337** [comment]
updated now as i can see
i'll close it
