### ISSUE TITLE
Freeze AI issue

### ISSUE THREAD

**Issue by KarmaMod** [Yeethan69/AIO#52]
There is an issue with Freeze AI that freezes yourself and sometimes doesn't freeze all AI. Requires to untick and tick again every races. Happens on both FH4 and 5. I tried the other trainer which has Freeze AI too and that worked perfectly
I'm wondering why no one reported the issue

https://streamja.com/P5qrX

**Comment by wpy20001125** [comment]
restart the game and turn the switch on before you enter the race

**Comment by KarmaMod** [comment]
Ok, I did and left it on. It worked
Wasn't able to try on FH5 rn because it updated and the author of AIO temp disabled it

Thanks
