### ISSUE TITLE
Velocity Speed not working

### ISSUE THREAD

**Issue by SteveZ33** [Yeethan69/AIO#54]
Hi, could you fix the Velocity Speed setting? It was super cool if you set it to 1.01000 because it worked like a little Nitro Boost but now it doesnt matter what values I put in, it instantly warps my car to 700kph and i fly through the map :(

thank you <3

**Comment by Sirojiddin007** [comment]
Hi, you can try the previous one 0.0.26 it works :), however, sometimes it can't scan the game. So, if u face this issue try to launch a new one then close it after the scan is complete, and switch to old(0.0.26). Check it out!

**Comment by SteveZ33** [comment]
> Hi, you can try the previous one 0.0.26 it works :), however, sometimes it can't scan the game. So, if u face this issue try to launch a new one then close it after the scan is complete, and switch to old(0.0.26). Check it out!

i can't get it to connect, no matter what i try, i also tried 0.25

**Comment by ItsLogic** [comment]
Try setting your system language to english (united kingdom) and see of that fixes the issue

**Comment by SteveZ33** [comment]
> Try setting your system language to english (united kingdom) and see if that fixes the issue

Windows Language or FH5? FH5 language does not work, it seems like the boost is just too high (100 instead of 1 or something) the boost up to value works, if i set 5 for example it wont boost over 5kph but if i drive 4 it instantly sends me anywhere with a speed of 800+ and i end up in mountains, over the ocean or in the sky

**Comment by Yeethan69** [comment]
Windows language

**Comment by SteveZ33** [comment]
> Windows language

Thats it, thank you, is it possible to make it work for german again? if not its also ok, UK works like in 0.26
