### ISSUE TITLE
Gravity/acceleration not work properly in FH5

### ISSUE THREAD

**Issue by ASF678** [Yeethan69/AIO#55]
Hey! Everything worked fine on version 0.26. With the update to 0.27 and higher, gravity and acceleration stopped working correctly.
Gravity works if you set integer values: 9.0, 11.0, etc. A value of 11.1 will break the game. 
Acceleration works if you set values ​​with 1 decimal place, for example 0.1, 0.2. In this case, if you click pull, the current value is rounded up, to 1.0. If you set values ​​with 2 or more decimal places, the game will break, and the car will fly up, as if the acceleration was set to 0.

**Comment by ItsLogic** [comment]
Whats your widows and game language?

**Comment by ASF678** [comment]
Win10 Pro 20H2, russian language

**Comment by ItsLogic** [comment]
Try setting your system language to english (united kingdom) and see of that fixes the issue

**Comment by ItsLogic** [comment]
setting system region to United Kingdom is currently the "fix" for this issue. Nothing in our codebase changed so we are assuming this is an external issue unrelated to us
