### ISSUE TITLE
Turn assist & rewind bugged

### ISSUE THREAD

**Issue by StickyPenis** [Yeethan69/AIO#57]
### What version of the aio were you running?

0.27-0.30

### Game

FH5

### Game Version

Cracked (online-fix)

### What is the bug?

When using turn assist, the game produced a very loud and distorted "sonic boom" kind of sound and it doesn't change volume with the game unless you completely mute it. It also accelerates like crazy without throttle and spins sometimes, this doesn't stop until I restart the game.

Sometimes when using rewind, the car will shoot up in the air uncontrollably. Only features enabled at that point were either super brake or stop all wheels. Doesn't happen everytime and haven't found any common factors.

Please tell me if I missed something.

**Comment by ItsLogic** [comment]
We are looking into this but its a pretty hard issue to solve since we cant debug on our own pcs. Something happened with the last update that broke a few things on the cool shit tab but only for some people. We havent been able to find anything obviously different between the games so im pretty much just guessing here.
Whats your game language?
Whats your pc/windows language?

**Comment by StickyPenis** [comment]
Game language is English, pc is Dutch with some random things in English idk why. Thanks man :)

**Comment by ItsLogic** [comment]
can you try changing your windows language to engish-gb and see if the issue is still there?
I was able to reproduce on dutch

**Comment by StickyPenis** [comment]
Changed the language and tested a few races with different cars and settings. Everything seems to work now, including turn assist, velocity, acceleration, etc. Never would've expected such a weird fix but it works :)

**Comment by ItsLogic** [comment]
It makes no sense to us either. Im guessing something updated and changed the way languages are handled. Glad to know that fixed it for you though so at least we know what the issue comes from now.
