### ISSUE TITLE
Not an issue, but i found something

### ISSUE THREAD

**Issue by StickyPenis** [Yeethan69/AIO#59]
### What version of the aio were you running?

0.31

### Game

FH5

### Game Version

Cracked (online-fix)

### What is the bug?

I filed a bug report a few days ago concerning velocity and a sound bug. Changing my system settings to English (GB) fixed this but I just accidentally found something that might be useful. 
I just changed the date format from English to Dutch (dd/mm/yyyy to dd-mm-yyyy) and the bug returned. When I reverted it to the "Match Windows display language" it fixed it.

Setting changed is found in control panel > clock and region > region: change date, time or number format.

Hope this helps, issue can be closed.

**Comment by ItsLogic** [comment]
yeah this was figured out a few days before you made this issue. Thanks though
