### ISSUE TITLE
[Bug]: Unlock Clothes doesn't stick

### ISSUE THREAD

**Issue by ValidSpider** [Yeethan69/AIO#61]
### What version of the aio were you running?

0.0.0.31

### Game

FH5

### Game Version

Microsoft store

### What is the bug?

Unlock clothes allows purchase of locked clothing however if other clothing is selected it locks again, purchase isn't permanent.

**Comment by ItsLogic** [comment]
This isnt a bug. Its the only way it could be implemented
Just select the clothes you want while the option is active and they will stay equiped until you change clothes
