### ISSUE TITLE
[Bug]: Unlock clothes crashes game 

### ISSUE THREAD

**Issue by LexxxyT** [Yeethan69/AIO#62]
### What version of the aio were you running?

0.31

### Game

FH5

### Game Version

Steam

### What is the bug?

Unlock clothes crashes game when selecting locked clothes. Game version is 1.430.371.0

**Comment by Yeethan69** [comment]
Fixed in version [0.0.0.35](https://github.com/Yeethan69/AIO/releases/tag/0.0.0.35)
