### ISSUE TITLE
Issues with credits editing

### ISSUE THREAD

**Issue by mohitmm2003** [Yeethan69/AIO#63]
I've got enough of credits but I'm not able to edit credits and set it to a lower value, so that I won't get banned. Is there any fix for it?

**Comment by LegitSoulja** [comment]
> I've got enough of credits but I'm not able to edit credits and set it to a lower value, so that I won't get banned. Is there any fix for it?

Buy some cars, and gift them away?

**Comment by ItsLogic** [comment]
see above. Just buy some cars and delete them or whatever
