### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gigamash77** [Yeethan69/AIO#65]
### What version of the aio were you running?

34

### Game

FH5

### Game Version

Steam

### What is the bug?

Since version 26 or 27 the Acceleration feature doesn't work properly anymore, or rather the way it should. ( Car bounces up and down and is uncontrollable.) Can you look over there again? In version 25 it worked perfectly, but unfortunately this version no longer injects, otherwise I would use this version.

best regards

**Comment by ItsLogic** [comment]
This is most likely due to your windows region format. If you change it to English united kingdom the issue should go away.
Re open the issue if it still happens

**Comment by Yeethan69** [comment]
Change your pc region to English (United Kingdom)
![image_2022-03-07_233421](https://user-images.githubusercontent.com/46374629/157136166-d0ec2fb1-d74a-499c-a667-aa884e15f56a.png)
