### ISSUE TITLE
[Bug]: Quick add cars => Add rare cars

### ISSUE THREAD

**Issue by IrcDirk** [Yeethan69/AIO#68]
### What version of the aio were you running?

0.0.0.36

### Game

FH5

### Game Version

Microsoft store

### What is the bug?

U got bug in **Quick add cars => Add rare cars** and its not working as it should. 

**Missing ";" in SQL statement.** 

Both MS and Steam are affected.

**Comment by Yeethan69** [comment]
Yeah, you right, thanks.
Fixed for next update.
👍🏻
