### ISSUE TITLE
Add all cars not working

### ISSUE THREAD

**Issue by BAWANGSONG** [Yeethan69/AIO#7]
I followed the instructions,i ticked the box,turned a car and saved and i waited and nothing happened.I am sure that windows defender hasn't block this and my hardware is not that bad(Intel 10870H +Nvidia 3070 Mobile,game installed on SSD).Some other players have tried this great tool in MS store ver and they succeeded,but this option didn't seem to work on my laptop.Idk if sth is wrong with the tool or FH5 itself.Plz help.

**Comment by IrcDirk** [comment]
What version of FH5 u got?

**Comment by BAWANGSONG** [comment]
Latest MS store ver.Imma check the specific version number.Brb

**Comment by IrcDirk** [comment]
No i mean: Normal, Deluxe or Premium?

**Comment by BAWANGSONG** [comment]
Normal.Accessed throuth XGP

**Comment by bhdrozgn** [comment]
> I followed the instructions,i ticked the box,turned a car and saved and i waited and nothing happened.I am sure that windows defender hasn't block this and my hardware is not that bad(Intel 10870H +Nvidia 3070 Mobile,game installed on SSD).Some other players have tried this great tool in MS store ver and they succeeded,but this option didn't seem to work on my laptop.Idk if sth is wrong with the tool or FH5 itself.Plz help.

I confirm the same thing happens to me

**Comment by IrcDirk** [comment]
Seems it only works on Premium version...

**Comment by ItsLogic** [comment]
The add all cars option seems to have some issues. It has taken some people upwards of 10 mins just to get the in game dialog box for the added cars and some people like yourself dont even get the dialog box. It is being looked at but its pretty hard to figure out the cause as both of us dont actually have the issue

**Comment by BAWANGSONG** [comment]
Some even spend up to 30 min to get that dialog box

**Comment by IrcDirk** [comment]
And to me on Steam it always stops on this BMW FE and doesnt add more cars. I got normal version on Steam and this car is like for Deluxe+ ???

**Comment by BAWANGSONG** [comment]
IDK.Hope the author can see this issue and fix it.

**Comment by BAWANGSONG** [comment]
> The add all cars option seems to have some issues. It has taken some people upwards of 10 mins just to get the in game dialog box for the added cars and some people like yourself dont even get the dialog box. It is being looked at but its pretty hard to figure out the cause as both of us dont actually have the issue

So is there any further plan that this tool will be updated soon to fit the new version?

**Comment by ItsLogic** [comment]
> IDK.Hope the author can see this issue and fix it.

We are aware but as I said its difficult to fix an issue you dont have yourself.


> So is there any further plan that this tool will be updated soon to fit the new version?

It has been updated for the new game version since the day after the update released.

**Comment by IrcDirk** [comment]
I think i found a workaround. Make all cars free first... Then add cars.

**Comment by BAWANGSONG** [comment]
> I think i found a workaround. Make all cars free first... Then add cars. Of course adding all cars might take time. But now i dont have the issue when it just stops when adding some cars.

Nope it might not be just that easy.Some cars like those in formula drift DLC and welcome pack DLC and car pass dlc will automatically check if u have those stuff bought.If no,then when u click on these cars it won't success even u make those cars free so another way to add those cars is needed just like the one already made in the aio tool

**Comment by TheChxice** [comment]
Your all's problem is that you are offline, the feature only works when the pc is connected to the internet.
