### ISSUE TITLE
AIO Map doesn't open/work[Bug]: 

### ISSUE THREAD

**Issue by mystikmunk** [Yeethan69/AIO#72]
### What version of the aio were you running?

0.0.0.39

### Game

FH5

### Game Version

Microsoft store

### What is the bug?

as the title says. that new map you added has never worked. it doesnt open at all.

**Comment by NoPromises6** [comment]
Aio version has expired? Opening cannot inject game

**Comment by ItsLogic** [comment]
Try deleting the forza mods aio folder in your documents and relaunching. It should redownload the map and all other assets
