### ISSUE TITLE
[Bug]: Does Not Inject Into FH5

### ISSUE THREAD

**Issue by Lmorthian** [Yeethan69/AIO#76]
### What version of the aio were you running?

0.0.0.41

### Game

FH5

### Game Version

Microsoft store

### What is the bug?

Either Im Doing Something Wrong Or It Doesn't Work, When I Open The Menu It Will Never Inject Into FH5.

**Comment by Lmorthian** [comment]
Could be That I Dont Have Administrator On My PC But I Know The Code

**Comment by Lmorthian** [comment]
oh nevermind i just need to give it time

**Comment by LegitSoulja** [comment]
Why do people keep thinking this tool injects into the game when it doesn’t… Smh
