### ISSUE TITLE
Memory Scanner Broken (again)

### ISSUE THREAD

**Issue by mystikmunk** [Yeethan69/AIO#79]
What version of the aio were you running?
0.0.0.41

Game
FH5

Game Version
Newest(series 7 update)
Microsoft Version

What is the bug?
as the title states, the Stats Editor has malfunctioned again. I've tried on 3 different PC's and 1 laptop. I've fully uninstalled AIO (including the folder within My Documents) but every time I run the Stats Editor only ONE result appears and its value is a massive negative number...Any ideas why or how to fix?

**Comment by ItsLogic** [comment]
The stats editor should be fixed now on the new version of the AIO. Update and close the issue if it is working again

**Comment by mystikmunk** [comment]
Just updated and checked. Memory scanner is working! Closing issue now. Tha k you
