### ISSUE TITLE
Use of a speed hack/mod in A class

### ISSUE THREAD

**Issue by Notspeedruner** [Yeethan69/AIO#80]
### What version of the aio were you running?

0.41

### Game

FH4

### Game Version

Microsoft store

### What is the bug?

I have never used the following
1. Modding XP
2. Modding Money
3. Modding Wheelspins (Regular & Super)
4. Getting impossible stunt & speed trap records
5. Modding in null cars/unreleased cars/etc... No cars you shouldn't be able to attain currently.

Only used "Wheelspeed Speed Hack and Turn Assist" 

I get This!
-----------------------
Forza Horizon 4  
Area  Matchmaking
Use of a speed hack/mod in A class
Ban a month
---------------------

Forza Safety Team (Forza Support)

Hello,
 
While we appreciate your passion regarding this enforcement and the time it took to submit an appeal, we cannot lift the suspension. Suspensions are only issued following a rigorous investigation of the account’s activity and conduct, confirming that a Code of Conduct violation occurred. We thoroughly reviewed the circumstances behind the enforcement and again confirmed that the violation occurred, and that enforcement action was warranted. As a result, we cannot adjust or remove the suspension.

Thank you,
Forza Safety Team

**Comment by ItsLogic** [comment]
yes you cheated online and someone reported you for cheating online...
