### ISSUE TITLE
[Bug]: Stat editor broken

### ISSUE THREAD

**Issue by MRdoomauzz** [Yeethan69/AIO#81]
### What version of the aio were you running?

0.0.0.43

### Game

FH5

### Game Version

Microsoft store

### What is the bug?

stats editor isnt working. When I open that tab, the scan button is dark and I cant click it

**Comment by ItsLogic** [comment]
The stats editor was recently updated can you check to see if this issue still persists?

**Comment by MRdoomauzz** [comment]
> The stats editor was recently updated can you check to see if this issue still persists?

Checked when update .47 was released the other day. Still have the same issues

**Comment by ItsLogic** [comment]
Man what the fuck. I can't think of any reason why it can't find the correct address

**Comment by MRdoomauzz** [comment]
I don't know either. Unless there's some sort of authorization factor to the AIO where I would need permissions to use that part of it?

**Comment by ItsLogic** [comment]
Nope. If the rest of the aio works (autoshow/garage and cool shit) then there shouldn't be any permission issues. The app shouldn't even launch without admin anyway.
Can you give me as much info about your system as possible so I can try to troubleshoot?
Stuff like game language, game settings pc language, specs, other running programs, winver

There must be something different about your system compared to mine or anyone else who it works for

**Comment by MRdoomauzz** [comment]
I'm currently at work, but I will get those details as soon as possible

**Comment by MRdoomauzz** [comment]
Im finally on my weekend. What all specs of my pc are you needing?

**Comment by MRdoomauzz** [comment]
Update: stats still doesnt work with version .48. Im just as confused as you are as to why it doesnt work for me, yet I seem to be the only one having this issue

**Comment by ItsLogic** [comment]
> Im finally on my weekend. What all specs of my pc are you needing?
I ended up going away for a few days but im back now

Can you send over your:
cpu
ram
winver
game language
windows language
windows region
game settings (for graphics and other stuff like on screen readers or whatever)


The fucky wucky is interesting too. As long as you dont have any other issues it should go away if you delete the "Forza Mods Tool" folder in your documents and the speedhack.ini wherever the tool is

**Comment by MRdoomauzz** [comment]
cpu: Intel i7 8700
game language: English
windows language: English
region: US
all game graphics set to medium (can get more detailed when I get home in a couple hours)
ram: I believe 16GB DDR4

**Comment by ItsLogic** [comment]
Nah it wouldnt. Those are just the issue templates and the readme. They dont have anything to do with the tool functioning

**Comment by MRdoomauzz** [comment]
Alright. Here in a minute, I'm gonna try deleting those files you suggested and see what that does

**Comment by ItsLogic** [comment]
You know what I think thats it. It grabs some data on launch thats used for the stats editor so if your AV is blocking it then that is probably why the button is greyed out. If you were to whitelist `https://raw.githubusercontent.com/Yeethan69/AIOinfo/main/aioUpdate.txt` The button should at least enable

The internet connectivity on launch is for the auto updater (it queries another repo to see if there is a new version of the tool) and for a one time download of some extra files that would be too bulky to pack into the exe. It grabs some resources for the in tool map and some FH4 savegames. The fuckywucky on launch is usually due to these being missing or partially missing.

**Comment by MRdoomauzz** [comment]
That makes much more sense. I'm about to leave for work, but I'll give that a shot tomorrow and let you know if it fixes the problem

**Comment by MRdoomauzz** [comment]
whitelisting the AIO through my VP fixed the issue
