### ISSUE TITLE
[Bug]: FH4 update patched

### ISSUE THREAD

**Issue by Raymond4720** [Yeethan69/AIO#86]
### What version of the aio were you running?

0.0.0.44

### Game

FH4

### Game Version

Microsoft store

### What is the bug?

FH4 have patched an update and Forza Mods AIO hack Tool no longer attaches. Please fix. Thanks.

**Comment by ItsLogic** [comment]
We are aware and will push a hotfix when we get a chance. Currently FH4 isnt very high on the priority list though

**Comment by ItsLogic** [comment]
fixed in 0.0.0.47
