### ISSUE TITLE
[Feature-Request]: 1932 Ford DeLuxe Five-Window Coupe Forza Edition

### ISSUE THREAD

**Issue by Anton01359** [Yeethan69/AIO#88]
### Game

FH5

### What feature are you requesting?

The game has a car - 1932 Ford DeLuxe Five-Window Coupe Forza Edition, but you can get it on the steam version of the game only through technical support, having previously purchased a limited edition xbox controller, I have not found another way to contact you, so I write here, I apologize, so: I can somehow get this car through your cheat without getting banned, for example, by adding all the cars to the garage or I won't be able to drive it without purchasing a special DLC in the xbox version of the game? Of course I would like to have the opportunity to try this car)

**Comment by ItsLogic** [comment]
You need to redeem the controller code on microsoft store and play on that platform. The aio will not unlock the car as it is piracy

We will not implement it
