### ISSUE TITLE
[Feature-Request]: Restore car prices in a shop?

### ISSUE THREAD

**Issue by ostanislaw** [Yeethan69/AIO#91]
### Game

FH5

### What feature are you requesting?

I would like to be able to restore prices after enabling each car for free option. Is it possible?
Maybe need to overwrite some file in game folder to restore everything to default and keep just bought cars in current save?

**Comment by ostanislaw** [comment]
I've connected again and ticked/unticked "all cars free" option (don't know if it was necessary). Then I found what I was looking for, adding all car pass cars. I don't know how it was supposed to work (they were not bought instantly).
Then after PC reboot a miracle - exactly what I wanted to achive:
1. Every car from car pack is free.
2. Car pass cars are listed in car pack menu ready to be bought for free (previously there was none because I'm offline ;) )
3. Every other car has it's original price.

Great. Ticket could be closed.
Please just find my feedback that car pass cars option was not easy to find, maybe it would be nice to give a hint in Readme.

**Comment by ItsLogic** [comment]
Restoring car prices isnt possible. Its a one way edit and only stays live for the game session so if you want them reverted you just restart your game.

I will close the issue.
