### ISSUE TITLE
[Bug]: unlock decals feature not working.

### ISSUE THREAD

**Issue by marbleslovesyou** [Yeethan69/AIO#93]
### What version of the aio were you running?

Release 0.0.0.49

### Game

FH5

### Game Version

Cracked (other) Please put the crack name/version into the issue box below

### What is the bug?

whenever i tick the box for the unlock decals thingy they don't show up anywhere like the manufacture decals/colors area         (non cracked xbox app for PC)

**Comment by ItsLogic** [comment]
this was solved on discord
![image](https://user-images.githubusercontent.com/38233332/180452973-c24d648c-9973-4624-8b49-312ff2b34478.png)
