### ISSUE TITLE
[Bug]: FH5, stats editor, saveswapper, live tuning broke

### ISSUE THREAD

**Issue by BotterManTingGoes** [Yeethan69/AIO#95]
### What version of the aio were you running?

0.0.0.49

### Game

FH5

### Game Version

Steam

### What is the bug?

Pictured below, stats editor cannot be interacted with at all. Save swapper and live tuning are not even accessible.
![image](https://user-images.githubusercontent.com/89749332/180254824-17d21c84-119d-4e8b-912d-7c26d8bf7fb9.png)

**Comment by ItsLogic** [comment]
Stats editor requires an internet connection at launch to grab some game info. When it cant access this then the button is disabled Saveswapper and live tuning do not work on FH5 and are therefore disabled
