### ISSUE TITLE
[Bug]: Downforce & stunt jump bugs

### ISSUE THREAD

**Issue by BotterManTingGoes** [Yeethan69/AIO#96]
### What version of the aio were you running?

0.0.0.49

### Game

FH5

### Game Version

Steam

### What is the bug?

With acceleration enabled (for example 0.2100000) and adjusted to a high value or a slightly better than default value to actually get acceleration bonuses on the car, when going over a stunt jump that requires air time or trying to get those new flying things at the hotwheels track, your car will instantly fall down off the edge as if gravity is very strong depending on how high you set acceleration. This also happens on the loop-de-loops on the hotwheels track where your car will bug out and sometimes not go around the loop or will but very dysfunctionally go around the loop.

**Comment by ItsLogic** [comment]
Acceleration increases the acceleration of all parts of the car including falling so this isn't really a bug it's just how the value works
